import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/chat_message.dart';

final chatServiceProvider = Provider((ref) => ChatService());

class ChatService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Generate a consistent chatId for two users
  String getChatId(String uid1, String uid2) {
    List<String> ids = [uid1, uid2];
    ids.sort(); // Ensure chatId is always the same regardless of who starts
    return ids.join('_');
  }

  // Stream of messages for a specific chat
  Stream<List<ChatMessage>> getMessages(String chatId) {
    return _db
        .collection('chats')
        .doc(chatId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ChatMessage.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Send a new message
  Future<void> sendMessage({
    required String chatId,
    required String senderId,
    required String receiverId,
    required String content,
  }) async {
    final message = ChatMessage(
      id: '', // Auto-generated by Firestore
      senderId: senderId,
      receiverId: receiverId,
      content: content,
      timestamp: DateTime.now(),
    );

    final batch = _db.batch();

    // 1. Add message to sub-collection
    final msgRef = _db.collection('chats').doc(chatId).collection('messages').doc();
    batch.set(msgRef, message.toMap());

    // 2. Update chat metadata (last message, timestamp)
    final chatRef = _db.collection('chats').doc(chatId);
    batch.set(chatRef, {
      'lastMessage': content,
      'lastTimestamp': FieldValue.serverTimestamp(),
      'participants': [senderId, receiverId],
    }, SetOptions(merge: true));

    await batch.commit();
  }

  // Mark messages as read
  Future<void> markAsRead(String chatId, String userId) async {
    final snapshot = await _db
        .collection('chats')
        .doc(chatId)
        .collection('messages')
        .where('receiverId', isEqualTo: userId)
        .where('isRead', isEqualTo: false)
        .get();

    final batch = _db.batch();
    for (var doc in snapshot.docs) {
      batch.update(doc.reference, {'isRead': true});
    }
    await batch.commit();
  }

  // AI Assistant Mock Method (Used by Member Dashboard Assistant Tab)
  Future<String> sendAssistantMessage(String message) async {
    await Future.delayed(const Duration(seconds: 1));
    final msg = message.toLowerCase();
    if (msg.contains('pain') || msg.contains('hurt')) {
      return "I'm sorry to hear that. I recommend adjusting your chair so your feet are flat and taking a 5-minute walking break. If pain persists, consult your advisor.";
    }
    if (msg.contains('sara') || msg.contains('ahmed')) {
      return "Sara Ahmed is a patient currently assigned to the orthopedic department. Her posture compliance has improved by 15% this week.";
    }
    return "Based on your recent posture readings, try to keep your shoulders back and monitor your forward head posture. You're doing great!";
  }
}
