// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-xv0JhiSfTiIoCJrJwTkkbdcYjzkO6o',
    appId: '1:860063260168:web:71c45d5a0b82f7d882fbbd',
    messagingSenderId: '860063260168',
    projectId: 'smart-brace-app',
    authDomain: 'smart-brace-app.firebaseapp.com',
    storageBucket: 'smart-brace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7PPgTE9D0hjlxObuypcr4U7Vi9fYHOA',
    appId: '1:860063260168:android:4d0ee705ee291e7382fbbd',
    messagingSenderId: '860063260168',
    projectId: 'smart-brace-app',
    storageBucket: 'smart-brace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQRE3mPIMI0dPrQh79fkhlRBGNpgbbzgk',
    appId: '1:860063260168:ios:68ff7f64ec8830e182fbbd',
    messagingSenderId: '860063260168',
    projectId: 'smart-brace-app',
    storageBucket: 'smart-brace-app.firebasestorage.app',
    iosBundleId: 'com.smartposture.smartPostureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQRE3mPIMI0dPrQh79fkhlRBGNpgbbzgk',
    appId: '1:860063260168:ios:68ff7f64ec8830e182fbbd',
    messagingSenderId: '860063260168',
    projectId: 'smart-brace-app',
    storageBucket: 'smart-brace-app.firebasestorage.app',
    iosBundleId: 'com.smartposture.smartPostureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT-xv0JhiSfTiIoCJrJwTkkbdcYjzkO6o',
    appId: '1:860063260168:web:5f559d4564eb8acd82fbbd',
    messagingSenderId: '860063260168',
    projectId: 'smart-brace-app',
    authDomain: 'smart-brace-app.firebaseapp.com',
    storageBucket: 'smart-brace-app.firebasestorage.app',
  );
}
